/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PingRouteImport } from './routes/ping'
import { Route as privateRouteRouteImport } from './routes/(private)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as privateIndexRouteImport } from './routes/(private)/index'
import { Route as privateProfileRouteImport } from './routes/(private)/profile'
import { Route as privatePortfolioRouteImport } from './routes/(private)/portfolio'
import { Route as privateJobsRouteImport } from './routes/(private)/jobs'
import { Route as privateCompaniesRouteImport } from './routes/(private)/companies'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authSigninRouteImport } from './routes/(auth)/signin'
import { Route as privatePostsPostIdRouteImport } from './routes/(private)/posts.$postId'
import { Route as privateProfileUserIdPortfolioRouteImport } from './routes/(private)/profile.$userId.portfolio'
import { Route as privateEmpleosEmpleoIdAplicacionesRouteImport } from './routes/(private)/empleos.$empleoId.aplicaciones'

const PingRoute = PingRouteImport.update({
  id: '/ping',
  path: '/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const privateRouteRoute = privateRouteRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const privateIndexRoute = privateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => privateRouteRoute,
} as any)
const privateProfileRoute = privateProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => privateRouteRoute,
} as any)
const privatePortfolioRoute = privatePortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => privateRouteRoute,
} as any)
const privateJobsRoute = privateJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => privateRouteRoute,
} as any)
const privateCompaniesRoute = privateCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => privateRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authSigninRoute = authSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => authRouteRoute,
} as any)
const privatePostsPostIdRoute = privatePostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => privateRouteRoute,
} as any)
const privateProfileUserIdPortfolioRoute =
  privateProfileUserIdPortfolioRouteImport.update({
    id: '/$userId/portfolio',
    path: '/$userId/portfolio',
    getParentRoute: () => privateProfileRoute,
  } as any)
const privateEmpleosEmpleoIdAplicacionesRoute =
  privateEmpleosEmpleoIdAplicacionesRouteImport.update({
    id: '/empleos/$empleoId/aplicaciones',
    path: '/empleos/$empleoId/aplicaciones',
    getParentRoute: () => privateRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/ping': typeof PingRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/companies': typeof privateCompaniesRoute
  '/jobs': typeof privateJobsRoute
  '/portfolio': typeof privatePortfolioRoute
  '/profile': typeof privateProfileRouteWithChildren
  '/': typeof privateIndexRoute
  '/posts/$postId': typeof privatePostsPostIdRoute
  '/empleos/$empleoId/aplicaciones': typeof privateEmpleosEmpleoIdAplicacionesRoute
  '/profile/$userId/portfolio': typeof privateProfileUserIdPortfolioRoute
}
export interface FileRoutesByTo {
  '/ping': typeof PingRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/companies': typeof privateCompaniesRoute
  '/jobs': typeof privateJobsRoute
  '/portfolio': typeof privatePortfolioRoute
  '/profile': typeof privateProfileRouteWithChildren
  '/': typeof privateIndexRoute
  '/posts/$postId': typeof privatePostsPostIdRoute
  '/empleos/$empleoId/aplicaciones': typeof privateEmpleosEmpleoIdAplicacionesRoute
  '/profile/$userId/portfolio': typeof privateProfileUserIdPortfolioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(private)': typeof privateRouteRouteWithChildren
  '/ping': typeof PingRoute
  '/(auth)/signin': typeof authSigninRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(private)/companies': typeof privateCompaniesRoute
  '/(private)/jobs': typeof privateJobsRoute
  '/(private)/portfolio': typeof privatePortfolioRoute
  '/(private)/profile': typeof privateProfileRouteWithChildren
  '/(private)/': typeof privateIndexRoute
  '/(private)/posts/$postId': typeof privatePostsPostIdRoute
  '/(private)/empleos/$empleoId/aplicaciones': typeof privateEmpleosEmpleoIdAplicacionesRoute
  '/(private)/profile/$userId/portfolio': typeof privateProfileUserIdPortfolioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/ping'
    | '/signin'
    | '/signup'
    | '/companies'
    | '/jobs'
    | '/portfolio'
    | '/profile'
    | '/'
    | '/posts/$postId'
    | '/empleos/$empleoId/aplicaciones'
    | '/profile/$userId/portfolio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/ping'
    | '/signin'
    | '/signup'
    | '/companies'
    | '/jobs'
    | '/portfolio'
    | '/profile'
    | '/'
    | '/posts/$postId'
    | '/empleos/$empleoId/aplicaciones'
    | '/profile/$userId/portfolio'
  id:
    | '__root__'
    | '/(auth)'
    | '/(private)'
    | '/ping'
    | '/(auth)/signin'
    | '/(auth)/signup'
    | '/(private)/companies'
    | '/(private)/jobs'
    | '/(private)/portfolio'
    | '/(private)/profile'
    | '/(private)/'
    | '/(private)/posts/$postId'
    | '/(private)/empleos/$empleoId/aplicaciones'
    | '/(private)/profile/$userId/portfolio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  privateRouteRoute: typeof privateRouteRouteWithChildren
  PingRoute: typeof PingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ping': {
      id: '/ping'
      path: '/ping'
      fullPath: '/ping'
      preLoaderRoute: typeof PingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/': {
      id: '/(private)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof privateIndexRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/profile': {
      id: '/(private)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof privateProfileRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/portfolio': {
      id: '/(private)/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof privatePortfolioRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/jobs': {
      id: '/(private)/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof privateJobsRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/companies': {
      id: '/(private)/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof privateCompaniesRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(private)/posts/$postId': {
      id: '/(private)/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof privatePostsPostIdRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/profile/$userId/portfolio': {
      id: '/(private)/profile/$userId/portfolio'
      path: '/$userId/portfolio'
      fullPath: '/profile/$userId/portfolio'
      preLoaderRoute: typeof privateProfileUserIdPortfolioRouteImport
      parentRoute: typeof privateProfileRoute
    }
    '/(private)/empleos/$empleoId/aplicaciones': {
      id: '/(private)/empleos/$empleoId/aplicaciones'
      path: '/empleos/$empleoId/aplicaciones'
      fullPath: '/empleos/$empleoId/aplicaciones'
      preLoaderRoute: typeof privateEmpleosEmpleoIdAplicacionesRouteImport
      parentRoute: typeof privateRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authSigninRoute: typeof authSigninRoute
  authSignupRoute: typeof authSignupRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSigninRoute: authSigninRoute,
  authSignupRoute: authSignupRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface privateProfileRouteChildren {
  privateProfileUserIdPortfolioRoute: typeof privateProfileUserIdPortfolioRoute
}

const privateProfileRouteChildren: privateProfileRouteChildren = {
  privateProfileUserIdPortfolioRoute: privateProfileUserIdPortfolioRoute,
}

const privateProfileRouteWithChildren = privateProfileRoute._addFileChildren(
  privateProfileRouteChildren,
)

interface privateRouteRouteChildren {
  privateCompaniesRoute: typeof privateCompaniesRoute
  privateJobsRoute: typeof privateJobsRoute
  privatePortfolioRoute: typeof privatePortfolioRoute
  privateProfileRoute: typeof privateProfileRouteWithChildren
  privateIndexRoute: typeof privateIndexRoute
  privatePostsPostIdRoute: typeof privatePostsPostIdRoute
  privateEmpleosEmpleoIdAplicacionesRoute: typeof privateEmpleosEmpleoIdAplicacionesRoute
}

const privateRouteRouteChildren: privateRouteRouteChildren = {
  privateCompaniesRoute: privateCompaniesRoute,
  privateJobsRoute: privateJobsRoute,
  privatePortfolioRoute: privatePortfolioRoute,
  privateProfileRoute: privateProfileRouteWithChildren,
  privateIndexRoute: privateIndexRoute,
  privatePostsPostIdRoute: privatePostsPostIdRoute,
  privateEmpleosEmpleoIdAplicacionesRoute:
    privateEmpleosEmpleoIdAplicacionesRoute,
}

const privateRouteRouteWithChildren = privateRouteRoute._addFileChildren(
  privateRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  privateRouteRoute: privateRouteRouteWithChildren,
  PingRoute: PingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
